/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.AtualizadorHora;
import modelo.ModeloVenda;
import controle.ConectaBanco;
import controle.ControleVenda;
import controle.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import controle.AtualizadorHora;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author bookafe
 */
public class FrmCardapio extends javax.swing.JFrame {
   
    ConectaBanco conn = new ConectaBanco();
    ConectaBanco conitens = new ConectaBanco();
    ModeloVenda mod = new ModeloVenda();
    controle.ControleVenda control = new ControleVenda();
    DecimalFormat formato;
    int flag=1, codVenda;
    float preco_produto,total=0;
    private Object conecta;
    String produto;
    

    /**
     * Creates new form FrmCardapio
     */
    public FrmCardapio() {
        initComponents();
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(df.format(hoje));
        
        //JOptionPane.showMessageDialog(rootPane,"Bienvenue a le système du Bookafe");
        //jButtonBuscaProduto.setEnabled(false);
        AtualizadorHora.start(labelhorario);
        formato = new DecimalFormat("#0.00");
        this.setExtendedState(this.getExtendedState()|FrmCardapio.MAXIMIZED_BOTH);
        //preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda="+ codVenda);
      // preencherItensVenda("select * from itens_venda_produto where id_produto='"+jTextFieldProduto.getText()+"'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jButtonBuscaProdutos = new javax.swing.JButton();
        jTextFieldProduto = new javax.swing.JTextField();
        jTextFieldcod = new javax.swing.JTextField();
        jTextFieldValorItem = new javax.swing.JTextField();
        labelValorItem = new javax.swing.JLabel();
        labelValorItem4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelValorItem1 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonBuscaCliente = new javax.swing.JButton();
        jTextFieldcod2 = new javax.swing.JTextField();
        jTextFieldProduto2 = new javax.swing.JTextField();
        jTextFieldCliente = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonAlterar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jPanelCardapio = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProduto1 = new javax.swing.JTextField();
        labelValorItem2 = new javax.swing.JLabel();
        labelValorItem3 = new javax.swing.JLabel();
        labelValorTotal = new javax.swing.JLabel();
        jTextFieldValorTotal1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPagamento2 = new javax.swing.JComboBox();
        jButtonPaiementEspecies = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonBuscaProduto = new javax.swing.JButton();
        labelhorario = new javax.swing.JLabel();
        jTextFieldcod1 = new javax.swing.JTextField();
        jTextFieldcod3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableItensVendas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableItensVendas1 = new javax.swing.JTable();
        jLabelMesa = new javax.swing.JLabel();

        label1.setText("label1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cardapio");
        setBackground(new java.awt.Color(153, 51, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Bangla Sangam MN", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Quantité:");

        jTextFieldQuantidade.setBackground(new java.awt.Color(255, 204, 0));
        jTextFieldQuantidade.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        jTextFieldQuantidade.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQuantidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQuantidadeFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("valeur unt:");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTablePesquisa.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jTablePesquisa.setForeground(new java.awt.Color(102, 102, 102));
        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisa.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jTablePesquisa.setSelectionForeground(new java.awt.Color(255, 153, 0));
        jTablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePesquisa);

        jButtonBuscaProdutos.setBackground(new java.awt.Color(255, 153, 0));
        jButtonBuscaProdutos.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButtonBuscaProdutos.setForeground(new java.awt.Color(102, 0, 0));
        jButtonBuscaProdutos.setText("Produits");
        jButtonBuscaProdutos.setEnabled(false);
        jButtonBuscaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutosActionPerformed(evt);
            }
        });

        jTextFieldProduto.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldProduto.setForeground(new java.awt.Color(153, 0, 0));
        jTextFieldProduto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldProduto.setEnabled(false);
        jTextFieldProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldProdutoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldProdutoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldProdutoMouseReleased(evt);
            }
        });

        jTextFieldcod.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldcod.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldcod.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldcod.setEnabled(false);
        jTextFieldcod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldcodMouseClicked(evt);
            }
        });

        jTextFieldValorItem.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldValorItem.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldValorItem.setEnabled(false);
        jTextFieldValorItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldValorItemMouseClicked(evt);
            }
        });

        labelValorItem.setBackground(new java.awt.Color(255, 204, 0));
        labelValorItem.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        labelValorItem.setForeground(new java.awt.Color(255, 204, 0));
        labelValorItem.setText("0,00");

        labelValorItem4.setBackground(new java.awt.Color(255, 204, 0));
        labelValorItem4.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        labelValorItem4.setForeground(new java.awt.Color(255, 204, 0));
        labelValorItem4.setText("CHF");

        jLabel14.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("TOTAL:");

        labelValorItem1.setBackground(new java.awt.Color(255, 204, 0));
        labelValorItem1.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        labelValorItem1.setForeground(new java.awt.Color(255, 204, 0));
        labelValorItem1.setText("CHF");

        jTextFieldValorTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldValorTotal.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        jTextFieldValorTotal.setForeground(new java.awt.Color(255, 204, 0));
        jTextFieldValorTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldValorTotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorTotalFocusLost(evt);
            }
        });

        jButtonBuscaCliente.setBackground(new java.awt.Color(255, 153, 0));
        jButtonBuscaCliente.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jButtonBuscaCliente.setForeground(new java.awt.Color(204, 0, 0));
        jButtonBuscaCliente.setText("Table");
        jButtonBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaClienteActionPerformed(evt);
            }
        });

        jTextFieldcod2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldcod2.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldcod2.setEnabled(false);

        jTextFieldProduto2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldProduto2.setForeground(new java.awt.Color(153, 0, 0));
        jTextFieldProduto2.setEnabled(false);
        jTextFieldProduto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldProduto2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldProduto2MouseReleased(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldProduto2MouseEntered(evt);
            }
        });

        jTextFieldCliente.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldCliente.setForeground(new java.awt.Color(153, 0, 0));
        jTextFieldCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldCliente.setEnabled(false);

        jButtonAlterar.setBackground(new java.awt.Color(255, 153, 0));
        jButtonAlterar.setFont(new java.awt.Font("Adobe Arabic", 1, 24)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(102, 0, 0));
        jButtonAlterar.setText("ACRESCENTAR");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonDeletar.setBackground(new java.awt.Color(255, 153, 0));
        jButtonDeletar.setFont(new java.awt.Font("Adobe Arabic", 1, 24)); // NOI18N
        jButtonDeletar.setForeground(new java.awt.Color(102, 0, 0));
        jButtonDeletar.setText("DELETAR");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(255, 153, 0));
        jButtonAdd.setFont(new java.awt.Font("Adobe Arabic", 1, 24)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(102, 0, 0));
        jButtonAdd.setText("INCLUIR");
        jButtonAdd.setEnabled(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldcod, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelValorItem, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonBuscaProdutos)
                                    .addComponent(jTextFieldProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addComponent(jTextFieldcod2, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(30, 30, 30)
                                .addComponent(labelValorItem1))
                            .addComponent(labelValorItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCliente))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonBuscaProdutos)
                        .addGap(69, 69, 69)
                        .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(labelValorItem1))
                    .addComponent(jTextFieldProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(labelValorItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        jPanelCardapio.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/images (2)_1.png"))); // NOI18N
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Articles:");

        jTextFieldProduto1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldProduto1.setForeground(new java.awt.Color(153, 0, 0));
        jTextFieldProduto1.setEnabled(false);
        jTextFieldProduto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldProduto1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldProduto1MouseReleased(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldProduto1MouseEntered(evt);
            }
        });

        labelValorItem2.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        labelValorItem2.setForeground(new java.awt.Color(255, 255, 51));
        labelValorItem2.setText("0,00");

        labelValorItem3.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        labelValorItem3.setForeground(new java.awt.Color(255, 255, 51));
        labelValorItem3.setText("0,00");

        labelValorTotal.setBackground(new java.awt.Color(255, 204, 0));
        labelValorTotal.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        labelValorTotal.setForeground(new java.awt.Color(255, 153, 0));
        labelValorTotal.setText("0,00");
        labelValorTotal.setEnabled(false);

        jTextFieldValorTotal1.setBackground(new java.awt.Color(255, 204, 0));
        jTextFieldValorTotal1.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        jTextFieldValorTotal1.setForeground(new java.awt.Color(153, 0, 0));
        jTextFieldValorTotal1.setEnabled(false);
        jTextFieldValorTotal1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldValorTotal1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorTotal1FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Al Nile", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caputino.jpeg"))); // NOI18N
        jLabel5.setText("BOISSONS:");

        jComboBoxPagamento2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jComboBoxPagamento2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A vista", "Parcelado" }));
        jComboBoxPagamento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxPagamento2MouseClicked(evt);
            }
        });
        jComboBoxPagamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPagamento2ActionPerformed(evt);
            }
        });

        jButtonPaiementEspecies.setBackground(new java.awt.Color(255, 153, 0));
        jButtonPaiementEspecies.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButtonPaiementEspecies.setForeground(new java.awt.Color(153, 0, 0));
        jButtonPaiementEspecies.setText("Finalizer Paiement ");
        jButtonPaiementEspecies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPaiementEspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaiementEspeciesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCardapioLayout = new javax.swing.GroupLayout(jPanelCardapio);
        jPanelCardapio.setLayout(jPanelCardapioLayout);
        jPanelCardapioLayout.setHorizontalGroup(
            jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCardapioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCardapioLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCardapioLayout.createSequentialGroup()
                        .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))))
            .addGroup(jPanelCardapioLayout.createSequentialGroup()
                .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCardapioLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPagamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCardapioLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel10))))
                    .addGroup(jPanelCardapioLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButtonPaiementEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCardapioLayout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(jTextFieldProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
            .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCardapioLayout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(labelValorItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(139, Short.MAX_VALUE)))
            .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCardapioLayout.createSequentialGroup()
                    .addContainerGap(149, Short.MAX_VALUE)
                    .addComponent(labelValorItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(326, 326, 326)))
        );
        jPanelCardapioLayout.setVerticalGroup(
            jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardapioLayout.createSequentialGroup()
                .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCardapioLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel10))
                    .addGroup(jPanelCardapioLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addComponent(jComboBoxPagamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jButtonPaiementEspecies)
                .addGap(508, 508, 508)
                .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCardapioLayout.createSequentialGroup()
                    .addGap(1018, 1018, 1018)
                    .addComponent(jTextFieldProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1324, Short.MAX_VALUE)))
            .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCardapioLayout.createSequentialGroup()
                    .addGap(1075, 1075, 1075)
                    .addComponent(labelValorItem2)
                    .addContainerGap(1235, Short.MAX_VALUE)))
            .addGroup(jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCardapioLayout.createSequentialGroup()
                    .addGap(1085, 1085, 1085)
                    .addComponent(labelValorItem3)
                    .addContainerGap(1225, Short.MAX_VALUE)))
        );

        jLabel8.setBackground(new java.awt.Color(153, 0, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/bookafe.jpeg"))); // NOI18N
        jLabel8.setText("Bookafe Geneve");

        jButtonBuscaProduto.setBackground(new java.awt.Color(102, 0, 0));
        jButtonBuscaProduto.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButtonBuscaProduto.setForeground(new java.awt.Color(102, 0, 0));
        jButtonBuscaProduto.setText("Horaire:");
        jButtonBuscaProduto.setEnabled(false);
        jButtonBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutoActionPerformed(evt);
            }
        });

        labelhorario.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        labelhorario.setForeground(new java.awt.Color(255, 153, 0));
        labelhorario.setText("Horaire");

        jTextFieldcod1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldcod1.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldcod1.setEnabled(false);
        jTextFieldcod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldcod1MouseClicked(evt);
            }
        });

        jTextFieldcod3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldcod3.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldcod3.setEnabled(false);
        jTextFieldcod3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldcod3MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 0));
        jLabel15.setText("Table");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 0));
        jLabel13.setText("Data:");

        jFormattedTextFieldData.setForeground(new java.awt.Color(102, 0, 0));
        jFormattedTextFieldData.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jFormattedTextFieldData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataFocusGained(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTableItensVendas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableItensVendas.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jTableItensVendas.setForeground(new java.awt.Color(204, 0, 0));
        jTableItensVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableItensVendas.setSelectionForeground(new java.awt.Color(255, 153, 0));
        jTableItensVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensVendasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableItensVendas);

        jTableItensVendas1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableItensVendas1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jTableItensVendas1.setForeground(new java.awt.Color(204, 0, 0));
        jTableItensVendas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableItensVendas1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTableItensVendas1.setSelectionForeground(new java.awt.Color(255, 153, 0));
        jTableItensVendas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensVendas1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableItensVendas1);

        jLabelMesa.setBackground(new java.awt.Color(255, 204, 0));
        jLabelMesa.setFont(new java.awt.Font("Adobe Arabic", 1, 48)); // NOI18N
        jLabelMesa.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMesa.setText("Table n°");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMesa)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldcod3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jButtonBuscaProduto)
                        .addGap(33, 33, 33)
                        .addComponent(labelhorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(51, 51, 51)
                        .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanelCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1023, 1023, 1023)
                    .addComponent(jTextFieldcod1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(736, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldcod3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBuscaProduto)
                                .addComponent(labelhorario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(211, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1067, 1067, 1067)
                    .addComponent(jTextFieldcod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1816, 835));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPaiementEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaiementEspeciesActionPerformed
        // TODO add your handling code here:
        if(jComboBoxPagamento2.getSelectedItem().equals("A vista")){
        mod.setIdVenda(codVenda);
        mod.setMesaCliente(jTextFieldCliente.getText());
        mod.setData(jFormattedTextFieldData.getText());
        mod.setValorVenda(Float.parseFloat(jTextFieldValorTotal.getText()));
        mod.setPagamento((String)jComboBoxPagamento2.getSelectedItem());
        control.FechaVenda(mod);
        dispose();
        }else{
           
        mod.setIdVenda(codVenda);
        mod.setMesaCliente(jTextFieldCliente.getText());
        mod.setData(jFormattedTextFieldData.getText());
        mod.setValorVenda(Float.parseFloat(jTextFieldValorTotal.getText()));
        mod.setPagamento((String)jComboBoxPagamento2.getSelectedItem());
        control.FechaVenda(mod);
        FrmParcelamentoVenda frm = new FrmParcelamentoVenda(codVenda);
        frm.setVisible(true);
        dispose();  
        }
        

    
             
        
    }//GEN-LAST:event_jButtonPaiementEspeciesActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
         
        try {
            
            int Venda,quantidade=0;
            int idVenda;
            int resul; 
            conn.conexao();
            conn.executaSQL("select * from produto where nome_produto='"+jTextFieldProduto.getText()+"'");
            conn.rs.first();
            
            quantidade = conn.rs.getInt("quantidade");
            if(quantidade>=Integer.parseInt(jTextFieldQuantidade.getText())){
            resul = quantidade-Integer.parseInt(jTextFieldQuantidade.getText());
            mod.setNomeProduto(jTextFieldProduto.getText());
            mod.setQtdItem(Integer.parseInt(jTextFieldQuantidade.getText()));
            mod.setIdVenda(codVenda);
            
            
//            formato = new DecimalFormat("#0.00");
//            Double num = (Double.parseDouble(jTextFieldValorTotal.getText()));
//            labelValorTotal.setText(formato.format(num));
            
            control.adicionaItem(mod);
            
//               formato = new DecimalFormat("#0.00");
//            Double num = (Double.parseDouble(jTextFieldValorTotal.getText()));
//            labelValorTotal.setText(formato.format(num));
            
            labelValorTotal.setText(jTextFieldValorTotal.getText());
           
        
        
            
            
            preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda="+ codVenda);
            } else{
               
                 JOptionPane.showMessageDialog(rootPane,"A quantidade desejada nao estar disponivel no estoque");
            }
            
            
            // total=total+Float.parseFloat(jTextFieldValorItem.getText())*Integer.parseInt(jTextFieldQuantidade.getText());
            //jTextFieldValorTotal.setText(String.valueOf(total));
            //preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda="+ codVenda);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jFormattedTextFieldDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataFocusGained
        // TODO add your handling code here:
        
        
        float valorTotal;
        valorTotal= Float.parseFloat(jTextFieldValorItem.getText())*Integer.parseInt(jTextFieldQuantidade.getText());
        jTextFieldValorTotal.setText(String.valueOf(total));
        
        labelValorTotal.setText(jTextFieldValorTotal.getText());
        
        
        
       
        
    }//GEN-LAST:event_jFormattedTextFieldDataFocusGained

    private void jTextFieldQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeFocusGained
        // TODO add your handling code here:
        
        
        float valorTotal;
        valorTotal= Float.parseFloat(jTextFieldValorItem.getText())*Integer.parseInt(jTextFieldQuantidade.getText());
        jTextFieldValorTotal.setText(String.valueOf(valorTotal));
              
//        ;
    
     
        
                
    }//GEN-LAST:event_jTextFieldQuantidadeFocusGained

    private void jTablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseClicked
        // TODO add your handling code here:
        //Float num= (Float.parseFloat(labelValorItem.getText()));
        if (flag==1){
            String mesas_cliente = "" +jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(),0);
            String mesa_cliente = "" +jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(),1);
           
            
            
            jTextFieldCliente.setText(mesa_cliente);
             jTextFieldcod3.setText(mesas_cliente);
             jTextFieldcod.setEnabled(true);
             jTextFieldProduto.setEnabled(true);
             jLabelMesa.setText(jTextFieldCliente.getText());
             jButtonAdd.setEnabled(true);       
             jButtonPaiementEspecies.setEnabled(true);
             jButtonAlterar.setEnabled(true);
             jButtonDeletar.setEnabled(true);
             jTextFieldCliente.setEnabled(true);
             jButtonBuscaProdutos.setEnabled(true);
             jTextFieldValorItem.setEnabled(true);
             
             //preencherVenda("select * from mesas inner join venda on mesas.id_mesa=venda.id_mesa where id_venda ='210'");
             preencherVenda("select * from venda inner join mesas on venda.id_mesa=mesas.id_mesa where numero_mesa = '"+jTextFieldCliente.getText()+"'");
             
             //preencherVenda("select * from venda where id_mesa='"+jTextFieldcod3.getText()+"'");
              
        }
        else{  conn.conexao();
                String nome_produto = "" +jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(),1);
                conn.executaSQL("select * from produto where nome_produto='"+nome_produto+"'");
            try {
//            
                conn.rs.first(); 
                jTextFieldcod.setText(String.valueOf(conn.rs.getInt("id_produto")));
                //jTextFieldcod2.setText(String.valueOf(conn.rs.getInt("id_produto")));
                preco_produto=conn.rs.getFloat("preco_venda");
                jTextFieldProduto.setText(nome_produto);
                //jTextFieldProduto2.setText(nome_produto);
                jTextFieldValorItem.setText(String.valueOf(preco_produto));
                labelValorItem.setText((jTextFieldValorItem.getText()));              
                jTextFieldQuantidade.setText("1");
                
//                formato = new DecimalFormat("#0.00");
//                Double num = (Double.parseDouble(jTextFieldValorItem.getText()));
//                labelValorItem.setText(formato.format(num));
                
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar o preço:"+ex);
                 conn.desconecta();
            }
        }
        
//        conn.conexao();
//        conexaoPesquisa.conexao();
//        conn.executaSQL("select * from fornecedores where nome_fornecedor='"+nome_fornecedor+"'");
//        
//        try {           
//            conn.rs.first();
//            jTextFieldCod.setText(String.valueOf(conn.rs.getInt("id_fornecedor")));
//            jTextFieldNomeForn.setText(conn.rs.getString("nome_fornecedor"));
//            jTextFieldEnd.setText(String.valueOf(conn.rs.getString("endereco")));
//            
//            conexaoPesquisa.executaSQL("select * from bairro where id_bairro=" +conn.rs.getInt("id_bairro"));          
//            conexaoPesquisa.rs.first();
//            jComboBoxBairro.setSelectedItem(conexaoPesquisa.rs.getString("nome_bairro"));
//            conexaoPesquisa.desconecta();
//            conn.desconecta();
//            jTextFieldEnd.setEnabled(true);
//            jTextFieldNomeForn.setEnabled(true);
//            jFormattedTextFieldCNPJ.setEnabled(true);
//            jButtonSalvar.setEnabled(true);
//            jButtonNovo.setEnabled(false);
//            jButtonEditar.setEnabled(true);
//            jButtonExcluir.setEnabled(true);               
//        } catch (SQLException s) {
//            
//            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ao selecionar os dados! n ERRO:"+s);
//            conexaoPesquisa.desconecta();
//            conn.desconecta();
//        }
//        
        
        
     
    }//GEN-LAST:event_jTablePesquisaMouseClicked

    private void jButtonBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaClienteActionPerformed
        // TODO add your handling code here:
        flag=1;
        //jButtonBuscaProdutos.setEnabled(true);
        //preencherTabelaCliente("select * from clientes where nome_cliente like '%" +jTextFieldCliente.getText()+ "%'");
        //preencherTabelaMesa("select * from mesas where numero_mesa like '%" +jTextFieldCliente.getText()+ "%'");
          preencherTabelaMesa("select * from mesas");
        
        
        
    }//GEN-LAST:event_jButtonBuscaClienteActionPerformed

    private void jButtonBuscaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutosActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane,"Digite o numero da mesa");
        conn.conexao();
        try {
            PreparedStatement pst = conn.conn.prepareStatement("insert into venda (valor_venda) values(?)");
            pst.setFloat(1, 0);
            pst.execute();
            conn.executaSQL("select * from venda");
            conn.rs.last();
            codVenda=conn.rs.getInt("id_venda");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro" + ex);  
        }
        flag=2;
        //preencherTabelaProduto("select * from produto where nome_produto like '%" +jTextFieldProduto.getText()+ "%'");
        preencherTabelaProduto("select * from produto");
    }//GEN-LAST:event_jButtonBuscaProdutosActionPerformed

    private void jButtonBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutoActionPerformed
        // TODO add your handling code here:
        conn.conexao();
        try {
            PreparedStatement pst = conn.conn.prepareStatement("insert into venda (valor_venda) values(?)");
            pst.setFloat(1, 0);
            pst.execute();
            conn.executaSQL("select * from venda");
            conn.rs.last();
            codVenda=conn.rs.getInt("id_venda");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro" + ex);
        }
        flag=2;
        preencherTabelaProduto("select * from produto where nome_produto like '%" +jTextFieldProduto.getText()+ "%'");
    }//GEN-LAST:event_jButtonBuscaProdutoActionPerformed

    private void jTextFieldProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProdutoMousePressed
        // TODO add your handling code here:
        //preencherTabelaProduto("select * from produto where nome_produto like '%" +jTextFieldProduto.getText()+ "%'");
    }//GEN-LAST:event_jTextFieldProdutoMousePressed

    private void jTextFieldProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProdutoMouseReleased
        // TODO add your handling code here:
        preencherTabelaProduto("select * from produto where nome_produto like '%" +jTextFieldProduto.getText()+ "%'");
    }//GEN-LAST:event_jTextFieldProdutoMouseReleased

    private void jTextFieldProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProdutoMouseEntered
        // TODO add your handling code here:
        //preencherTabelaProduto("select * from produto where nome_produto like '%" +jTextFieldProduto.getText()+ "%'");
    }//GEN-LAST:event_jTextFieldProdutoMouseEntered

    private void jComboBoxPagamento2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxPagamento2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagamento2MouseClicked

    private void jComboBoxPagamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPagamento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagamento2ActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
   
       int qtd=0; 
       int resul=0;
       int qtditens=0;
    ConectaBanco conect = new ConectaBanco(); 
    conn.conexao();
    conn.executaSQL("select * from itens_venda_produto where id_produto='"+jTextFieldcod.getText()+"'");
        try {
            conn.rs.first();
            qtditens = conn.rs.getInt("quantidade_produto");
            resul=qtditens+Integer.parseInt(jTextFieldQuantidade.getText());
            //JOptionPane.showMessageDialog(rootPane, resul);
            conn.executaSQL("update itens_venda_produto set quantidade_produto='"+resul+ "' where id_produto='"+jTextFieldcod.getText()+ "'");
            preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda="+ codVenda);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Quantidade nao deu certo:"+ex);
        }
   
       
       
       
    conn.conexao();
    conn.executaSQL("select * from produto where id_produto='"+jTextFieldcod.getText()+"'");
        try {
            conn.rs.first();       
            qtd = conn.rs.getInt("quantidade");
            if(qtd>=Integer.parseInt(jTextFieldQuantidade.getText())){
            resul=qtd-Integer.parseInt(jTextFieldQuantidade.getText());
            //JOptionPane.showMessageDialog(rootPane, resul);
            conn.executaSQL("update produto set quantidade='"+resul+"' where id_produto='"+jTextFieldcod.getText()+"'");
           // preencherTabelaProduto("select * from produto where id_produto='"+jTextFieldcod.getText()+ "'");
            preencherTabelaProduto("select * from produto ");
            
          }else{
                JOptionPane.showMessageDialog(rootPane, "Quantidade indisponivel no estoque");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro zt:"+ex);
        }
    
           
           
       
            
            
       
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableItensVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensVendasMouseClicked
        // TODO add your handling code here:
        
        
           
            conn.conexao();
            
        
            String nome_produto = "" +jTableItensVendas.getValueAt(jTableItensVendas.getSelectedRow(),0);
             String quantidade_produto = "" +jTableItensVendas.getValueAt(jTableItensVendas.getSelectedRow(),1);
             
                conn.executaSQL("select * from produto where nome_produto='"+nome_produto+"'");
                
        try {
            conn.rs.first();
            jTextFieldcod.setText(String.valueOf(conn.rs.getInt("id_produto")));
            jTextFieldcod2.setText(String.valueOf(conn.rs.getInt("id_produto")));
            jTextFieldProduto.setText(nome_produto);
            jTextFieldProduto2.setText(nome_produto);
            jTextFieldQuantidade.setText(quantidade_produto);
            preco_produto=conn.rs.getFloat("preco_venda");
            jTextFieldValorItem.setText(String.valueOf(preco_produto));
            
            
            
            
          
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(rootPane, "Erro ! n ERRO:"+ex);
              conn.desconecta();
              
        }
        
     
    }//GEN-LAST:event_jTableItensVendasMouseClicked

    private void jTextFieldProduto2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProduto2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProduto2MousePressed

    private void jTextFieldProduto2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProduto2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProduto2MouseReleased

    private void jTextFieldProduto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProduto2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProduto2MouseEntered

    private void jTextFieldProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoMouseClicked

    private void jTextFieldcodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldcodMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcodMouseClicked

    private void jTextFieldValorItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldValorItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorItemMouseClicked

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        // TODO add your handling code here:
       int qtd=0; 
       int resul=0;
       int qtditens=0;
       
       ConectaBanco conect = new ConectaBanco(); 
 
         conn.conexao();
         //conn.executaSQL("select * from itens_venda_produto where id_produto='"+jTextFieldcod2.getText()+"'");
        try {
            conn.rs.first();       
             conn.executaSQL("delete * from itens_venda_produto where id_produto='"+jTextFieldProduto2.getText()+"'");
            preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda="+ codVenda);
            //preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda='"+jTextFieldcod3.getText()+"'");          
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao deletar o item :"+ex);
        }
       conn.desconecta();
        
        
        conn.conexao();
        conn.executaSQL("select * from produto where id_produto='"+jTextFieldcod.getText()+"'");
        try {
            conn.rs.first();       
            qtd = conn.rs.getInt("quantidade");         
            resul=qtd+Integer.parseInt(jTextFieldQuantidade.getText());
            conn.executaSQL("update produto set quantidade='"+resul+"' where id_produto='"+jTextFieldcod.getText()+"'");
            preencherTabelaProduto("select * from produto ");
                      
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro zt:"+ex);
        }
//        
                 
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jTableItensVendas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensVendas1MouseClicked
        // TODO add your handling code here:
       
        
                 String codVendas = "" +jTableItensVendas1.getValueAt(jTableItensVendas1.getSelectedRow(),0);
           //jTVxtFieldcod3.setText(co);
        //preencherVenda("select * from mesas inner join venda on mesas.id_mesa=venda.id_mesa where id_venda ='210'");
        preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda='"+codVendas+"'"); 
    }//GEN-LAST:event_jTableItensVendas1MouseClicked

    private void jTextFieldcod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldcod1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcod1MouseClicked

    private void jTextFieldcod3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldcod3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcod3MouseClicked

    private void jTextFieldValorTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorTotalFocusGained
        // TODO add your handling code here:
        jTextFieldValorItem.setText(String.valueOf(Integer.parseInt(jTextFieldQuantidade.getText()) * Double.parseDouble(jTextFieldValorItem.getText())));
    }//GEN-LAST:event_jTextFieldValorTotalFocusGained

    private void jTextFieldValorTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorTotalFocusLost
        // TODO add your handling code here:
        jTextFieldValorItem.setText(String.valueOf(Integer.parseInt(jTextFieldQuantidade.getText()) * Double.parseDouble(jTextFieldValorItem.getText())));
    }//GEN-LAST:event_jTextFieldValorTotalFocusLost

    private void jTextFieldQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeFocusLost
        // TODO add your handling code here:
        jTextFieldValorTotal1.setText(String.valueOf(Integer.parseInt(jTextFieldQuantidade.getText()) * Double.parseDouble(jTextFieldValorItem.getText())));
    }//GEN-LAST:event_jTextFieldQuantidadeFocusLost

    private void jTextFieldValorTotal1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorTotal1FocusLost
        // TODO add your handling code here:

        //jTextFieldValorItem.setText(String.valueOf(Integer.parseInt(jTextFieldQuantidade.getText()) * Double.parseDouble(jTextFieldValorItem.getText())));

    }//GEN-LAST:event_jTextFieldValorTotal1FocusLost

    private void jTextFieldValorTotal1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorTotal1FocusGained
        // TODO add your handling code here:
        jTextFieldValorItem.setText(String.valueOf(Integer.parseInt(jTextFieldQuantidade.getText()) * Double.parseDouble(jTextFieldValorItem.getText())));
    }//GEN-LAST:event_jTextFieldValorTotal1FocusGained

    private void jTextFieldProduto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProduto1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProduto1MouseEntered

    private void jTextFieldProduto1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProduto1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProduto1MouseReleased

    private void jTextFieldProduto1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProduto1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProduto1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        control.CancelaVenda();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
   public void preencherTabelaCliente(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Codigo", "Mesa/Cliente"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      
                      dados.add(new Object[]{conn.rs.getString("id_cliente"), conn.rs.getString("nome_cliente")});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTablePesquisa.setModel(modelo);
               jTablePesquisa.getColumnModel ().getColumn(0).setPreferredWidth(100);
               jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
               jTablePesquisa.getColumnModel ().getColumn(1).setPreferredWidth(330);
               jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
               jTablePesquisa.getTableHeader().setReorderingAllowed(false);
               jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
               jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               conn.desconecta();
       }
   public void preencherTabelaMesa(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Codigo", "Numero de la Table/Client"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      
                      dados.add(new Object[]{conn.rs.getString("id_mesa"), conn.rs.getString("numero_mesa")});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTablePesquisa.setModel(modelo);
               jTablePesquisa.getColumnModel ().getColumn(0).setPreferredWidth(50);
               jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
               jTablePesquisa.getColumnModel ().getColumn(1).setPreferredWidth(460);
               jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
               jTablePesquisa.getTableHeader().setReorderingAllowed(false);
               jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
               jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               conn.desconecta();
                
       }
    public void preencherTabelaProduto(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Codigo", "Nome","Qtd"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      dados.add(new Object[]{conn.rs.getString("id_produto"), conn.rs.getString("nome_produto"),conn.rs.getString("quantidade")});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTablePesquisa.setModel(modelo);
               jTablePesquisa.getColumnModel ().getColumn(0).setPreferredWidth(70);
               jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
               jTablePesquisa.getColumnModel ().getColumn(1).setPreferredWidth(350);
               jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
               jTablePesquisa.getColumnModel ().getColumn(2).setPreferredWidth(100);
               jTablePesquisa.getColumnModel().getColumn(2).setResizable(false);
               jTablePesquisa.getTableHeader().setReorderingAllowed(false);
               jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
               jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               conn.desconecta();
                
       }
//    public void preencherTabelaBebidasfrias(String sql){
//       ArrayList dados = new ArrayList();
//       
//       String [] Colunas = new String[] {"Codigo", "Nome","Qtd"};
//               conn.conexao();
//               conn.executaSQL(sql);
//               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
//               try{
//                  conn.rs.first();
//                  do{
//                      dados.add(new Object[]{conn.rs.getString("id_bebida"), conn.rs.getString("nome_bebida"),conn.rs.getString("quantidade")});
//              }while(conn.rs.next());       
//                 }catch (SQLException ex){
//                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
//                   }  
//               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
//               jTablePesquisa1.setModel(modelo);
//               jTablePesquisa1.getColumnModel ().getColumn(0).setPreferredWidth(70);
//               jTablePesquisa1.getColumnModel().getColumn(0).setResizable(false);
//               jTablePesquisa1.getColumnModel ().getColumn(1).setPreferredWidth(350);
//               jTablePesquisa1.getColumnModel().getColumn(1).setResizable(false);
//               jTablePesquisa1.getColumnModel ().getColumn(2).setPreferredWidth(100);
//               jTablePesquisa1.getColumnModel().getColumn(2).setResizable(false);
//               jTablePesquisa1.getTableHeader().setReorderingAllowed(false);
//               jTablePesquisa1.setAutoResizeMode(jTablePesquisa1.AUTO_RESIZE_OFF);
//               jTablePesquisa1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//               conn.desconecta();
//                
//       }
//    public void preencherTabelaBebidasquentes(String sql){
//       ArrayList dados = new ArrayList();
//       
//       String [] Colunas = new String[] {"Codigo", "Nome","Qtd"};
//               conn.conexao();
//               conn.executaSQL(sql);
//               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
//               try{
//                  conn.rs.first();
//                  do{
//                      dados.add(new Object[]{conn.rs.getString("id_bebidaquente"), conn.rs.getString("nome_bebida"),conn.rs.getString("quantidade")});
//              }while(conn.rs.next());       
//                 }catch (SQLException ex){
//                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
//                   }  
//               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
//               jTablePesquisa1.setModel(modelo);
//               jTablePesquisa1.getColumnModel ().getColumn(0).setPreferredWidth(70);
//               jTablePesquisa1.getColumnModel().getColumn(0).setResizable(false);
//               jTablePesquisa1.getColumnModel ().getColumn(1).setPreferredWidth(350);
//               jTablePesquisa1.getColumnModel().getColumn(1).setResizable(false);
//               jTablePesquisa1.getColumnModel ().getColumn(2).setPreferredWidth(100);
//               jTablePesquisa1.getColumnModel().getColumn(2).setResizable(false);
//               jTablePesquisa1.getTableHeader().setReorderingAllowed(false);
//               jTablePesquisa1.setAutoResizeMode(jTablePesquisa1.AUTO_RESIZE_OFF);
//               jTablePesquisa1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//               conn.desconecta();
//                
//       }
    
//    public void preencherTabelaPatisserie(String sql){
//       ArrayList dados = new ArrayList();
//       
//       String [] Colunas = new String[] {"Codigo", "Nome","Qtd"};
//               conn.conexao();
//               conn.executaSQL(sql);
//               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
//               try{
//                  conn.rs.first();
//                  do{
//                      dados.add(new Object[]{conn.rs.getString("id_patsserie"), conn.rs.getString("nome_patisserie"),conn.rs.getString("quantidade")});
//              }while(conn.rs.next());       
//                 }catch (SQLException ex){
//                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
//                   }  
//               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
//               jTablePesquisa1.setModel(modelo);
//               jTablePesquisa1.getColumnModel ().getColumn(0).setPreferredWidth(70);
//               jTablePesquisa1.getColumnModel().getColumn(0).setResizable(false);
//               jTablePesquisa1.getColumnModel ().getColumn(1).setPreferredWidth(350);
//               jTablePesquisa1.getColumnModel().getColumn(1).setResizable(false);
//               jTablePesquisa1.getColumnModel ().getColumn(2).setPreferredWidth(100);
//               jTablePesquisa1.getColumnModel().getColumn(2).setResizable(false);
//               jTablePesquisa1.getTableHeader().setReorderingAllowed(false);
//               jTablePesquisa1.setAutoResizeMode(jTablePesquisa1.AUTO_RESIZE_OFF);
//               jTablePesquisa1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//               conn.desconecta();
//                
//       }
    public void preencherItensVenda(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Descricao", "Quantidade","Valor total"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      float valorProduto = conn.rs.getFloat("preco_venda");
                      int qtdVendida = conn.rs.getInt("quantidade_produto");
                      dados.add(new Object[]{conn.rs.getString("nome_produto"), conn.rs.getString("quantidade_produto"),valorProduto * qtdVendida});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTableItensVendas.setModel(modelo);
               jTableItensVendas.getColumnModel ().getColumn(0).setPreferredWidth(230);
               jTableItensVendas.getColumnModel().getColumn(0).setResizable(false);
               jTableItensVendas.getColumnModel ().getColumn(1).setPreferredWidth(80);
               jTableItensVendas.getColumnModel().getColumn(1).setResizable(false);
               jTableItensVendas.getColumnModel ().getColumn(2).setPreferredWidth(250);
               jTableItensVendas.getColumnModel().getColumn(2).setResizable(false);
               jTableItensVendas.getTableHeader().setReorderingAllowed(false);
               jTableItensVendas.setAutoResizeMode(jTableItensVendas.AUTO_RESIZE_OFF);
               jTableItensVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               SomaProduto();
               conn.desconecta();
                
       }
    public void preencherVenda(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Codigo_Venda", "Numero_Mesa","Data"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      dados.add(new Object[]{conn.rs.getString("id_venda"), conn.rs.getString("numero_mesa"),conn.rs.getString("data_venda")});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTableItensVendas1.setModel(modelo);
               jTableItensVendas1.getColumnModel ().getColumn(0).setPreferredWidth(100);
               jTableItensVendas1.getColumnModel().getColumn(0).setResizable(false);
               jTableItensVendas1.getColumnModel ().getColumn(1).setPreferredWidth(370);
               jTableItensVendas1.getColumnModel().getColumn(1).setResizable(false);
               jTableItensVendas1.getColumnModel ().getColumn(2).setPreferredWidth(320);
               jTableItensVendas1.getColumnModel().getColumn(2).setResizable(false);
               jTableItensVendas1.getTableHeader().setReorderingAllowed(false);
               jTableItensVendas1.setAutoResizeMode(jTableItensVendas1.AUTO_RESIZE_OFF);
               jTableItensVendas1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               SomaProduto();
               conn.desconecta();
                
       }

  public void SomaProduto(){
        total= 0;
        int qtd=0;
        float valor=0;
     
        conn.executaSQL("select * from itens_venda_produto inner join produto on itens_venda_produto.id_produto=produto.id_produto where id_venda="+codVenda);
        try {
            //conn.rs.first();
            while(conn.rs.next()){
                qtd = conn.rs.getInt("quantidade");
                valor = conn.rs.getFloat("preco_venda");
                total = total+ conn.rs.getFloat("preco_venda")* conn.rs.getInt("quantidade_produto");
                
            }
            jTextFieldValorTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscaCliente;
    private javax.swing.JButton jButtonBuscaProduto;
    private javax.swing.JButton jButtonBuscaProdutos;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonPaiementEspecies;
    private javax.swing.JComboBox jComboBoxPagamento2;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCardapio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableItensVendas;
    private javax.swing.JTable jTableItensVendas1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldProduto1;
    private javax.swing.JTextField jTextFieldProduto2;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldValorItem;
    private javax.swing.JTextField jTextFieldValorTotal;
    private javax.swing.JTextField jTextFieldValorTotal1;
    private javax.swing.JTextField jTextFieldcod;
    private javax.swing.JTextField jTextFieldcod1;
    private javax.swing.JTextField jTextFieldcod2;
    private javax.swing.JTextField jTextFieldcod3;
    private java.awt.Label label1;
    private javax.swing.JLabel labelValorItem;
    private javax.swing.JLabel labelValorItem1;
    private javax.swing.JLabel labelValorItem2;
    private javax.swing.JLabel labelValorItem3;
    private javax.swing.JLabel labelValorItem4;
    private javax.swing.JLabel labelValorTotal;
    private javax.swing.JLabel labelhorario;
    // End of variables declaration//GEN-END:variables
}
