/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.ModeloFornecedor;
import controle.ControleFornecedor;
import controle.ModeloTabela;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author bookafe
 */
public class FrmFornecedor extends javax.swing.JFrame {
    ConectaBanco conn = new ConectaBanco();
    ConectaBanco conexaoPesquisa = new ConectaBanco();
    ModeloFornecedor mod = new ModeloFornecedor();
    ControleFornecedor control = new ControleFornecedor();
    

    /**
     * Creates new form FrmFornecedor
     */
    public FrmFornecedor() {
        initComponents();
        conn.conexao();
        preencherCombobox();
        preencherTabela("select * from fornecedores");
        //preencherTabela("select * from fornecedores order by id_fornecedor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldNomeForn = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxBairro = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEnd = new javax.swing.JTextField();
        jLabelCid = new javax.swing.JLabel();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jLabelEstado = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPesquisar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedores");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Nome do Fornecedor:");

        jTextFieldCod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCod.setEnabled(false);

        jTextFieldNomeForn.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNomeForn.setEnabled(false);

        jButtonNovo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableFornecedor.setBackground(new java.awt.Color(51, 153, 255));
        jTableFornecedor.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTableFornecedor.setForeground(new java.awt.Color(0, 0, 51));
        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFornecedor);

        jButtonPrimeiro.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonPrimeiro.setText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonProximo.setText("Proximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonUltimo.setText("Ultimo");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gnome_logout.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Cnpj:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Bairro:");

        jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxBairroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxBairroMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxBairroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxBairroMouseEntered(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Endereço:");

        jTextFieldEnd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEnd.setEnabled(false);

        jFormattedTextFieldCNPJ.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButtonPesquisar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPesquisar1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonPesquisar1.setText("AddBairro");
        jButtonPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisar1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Cidade:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Estado:");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bookafes figurinha.jpeg"))); // NOI18N
        jLabel11.setText("Cidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButtonPrimeiro)
                        .addGap(100, 100, 100)
                        .addComponent(jButtonAnterior)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonProximo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addComponent(jLabelCid)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNomeForn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSair))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldCNPJ)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(jLabelEstado)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonPesquisar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)))))))))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUltimo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jButtonPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel9)))
                        .addGap(46, 46, 46)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonSair)
                                    .addComponent(jTextFieldNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCid)
                            .addComponent(jLabelEstado)
                            .addComponent(jButtonPesquisar1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNovo)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonExcluir)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonPesquisar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Cidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(402, 402, 402)
                    .addComponent(jLabel10)
                    .addContainerGap(452, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(283, 283, 283)
                    .addComponent(jLabel10)
                    .addContainerGap(211, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(906, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        jTextFieldEnd.setEnabled(true);
        jTextFieldNomeForn.setEnabled(true);
        jFormattedTextFieldCNPJ.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        mod.setNome(jTextFieldNomeForn.getText());
        mod.setEndereco(jTextFieldEnd.getText());
        mod.setCNPJ(jFormattedTextFieldCNPJ.getText());
        mod.setBairro((String)jComboBoxBairro.getSelectedItem());
       
        control.Salvar(mod);
        jTextFieldEnd.setEnabled(!true);
        jTextFieldNomeForn.setEnabled(!true);
        jTextFieldEnd.setText("");
        jTextFieldNomeForn.setText("");
        jTextFieldCod.setText("");
        jFormattedTextFieldCNPJ.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        preencherTabela("select * from fornecedores");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBairroMouseClicked
        // TODO add your handling code here:
//        jTextFieldEnd.setEnabled(true);
//        jTextFieldNomeForn.setEnabled(true);
//        jFormattedTextFieldCNPJ.setEnabled(true);
//        jButtonSalvar.setEnabled(true);
//        jButtonNovo.setEnabled(false);
//        jButtonEditar.setEnabled(true);
//        jButtonExcluir.setEnabled(true);
      
     
    }//GEN-LAST:event_jComboBoxBairroMouseClicked

    private void jComboBoxBairroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBairroMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxBairroMouseReleased

    private void jComboBoxBairroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBairroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBairroMousePressed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        mod.setNome(jTextFieldNomeForn.getText());
        mod.setEndereco(jTextFieldEnd.getText());
        mod.setCNPJ(jFormattedTextFieldCNPJ.getText());
        mod.setBairro((String)jComboBoxBairro.getSelectedItem());    
        control.Excluir(mod);
        jTextFieldEnd.setEnabled(!true);
        jTextFieldNomeForn.setEnabled(!true);
        jTextFieldEnd.setText("");
        jTextFieldNomeForn.setText("");
        jTextFieldCod.setText("");
        jFormattedTextFieldCNPJ.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
     
        
       
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxBairroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBairroMouseEntered
        // TODO add your handling code here:
        try {
            conn.conexao();
            conn.executaSQL("select * from bairro inner join cidade on bairro.id_cidade=cidade.id_cidade inner join estados on cidade.id_estado=estados.id_estado where nome_bairro='"+jComboBoxBairro.getSelectedItem()+"'");
            conn.rs.first();
            jLabelCid.setText(conn.rs.getString("nome_cidade"));
            jLabelEstado.setText(conn.rs.getString("sigla_estado"));
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar o bairro os bairros!"+ ex);
        }
     
    }//GEN-LAST:event_jComboBoxBairroMouseEntered

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        mod=control.Primeiro();
        jTextFieldCod.setText(""+mod.getId());
        jTextFieldNomeForn.setText(mod.getNome());
        jTextFieldEnd.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getCidade());
        jLabelCid.setText(mod.getCidade());
        jLabelEstado.setText(mod.getSigla_estado());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        mod.setId(Integer.parseInt(jTextFieldCod.getText()));
        mod.setNome(jTextFieldNomeForn.getText());
        mod.setEndereco(jTextFieldEnd.getText());
        mod.setCNPJ(jFormattedTextFieldCNPJ.getText());
        mod.setBairro((String)jComboBoxBairro.getSelectedItem());
        control.editar(mod);
        jTextFieldEnd.setEnabled(!true);
        jTextFieldNomeForn.setEnabled(!true);
        jTextFieldEnd.setText("");
        jTextFieldNomeForn.setText("");
        jTextFieldCod.setText("");
        jFormattedTextFieldCNPJ.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        preencherTabela("select * from fornecedores");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        jButtonEditar.setEnabled(true);
        
        
        preencherTabela("select * from fornecedores where nome_fornecedor like '%" +jTextFieldNomeForn.getText()+ "%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        mod=control.Ultimo();
        jTextFieldCod.setText(""+mod.getId());
        jTextFieldNomeForn.setText(mod.getNome());
        jTextFieldEnd.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getCidade());
        jLabelCid.setText(mod.getCidade());
        jLabelEstado.setText(mod.getSigla_estado());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        mod=control.Anterior();
        jTextFieldCod.setText(""+mod.getId());
        jTextFieldNomeForn.setText(mod.getNome());
        jTextFieldEnd.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getCidade());
        jLabelCid.setText(mod.getCidade());
        jLabelEstado.setText(mod.getSigla_estado());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        mod=control.proximo();
        jTextFieldCod.setText(""+mod.getId());
        jTextFieldNomeForn.setText(mod.getNome());
        jTextFieldEnd.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getCidade());
        jLabelCid.setText(mod.getCidade());
        jLabelEstado.setText(mod.getSigla_estado());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jTableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMouseClicked
        // TODO add your handling code here:

        String nome_fornecedor = "" +jTableFornecedor.getValueAt(jTableFornecedor.getSelectedRow(),1);  
//            
        conn.conexao();
        conexaoPesquisa.conexao();
        conn.executaSQL("select * from fornecedores where nome_fornecedor='"+nome_fornecedor+"'");
        
        try {           
            conn.rs.first();
            jTextFieldCod.setText(String.valueOf(conn.rs.getInt("id_fornecedor")));
            jTextFieldNomeForn.setText(conn.rs.getString("nome_fornecedor"));
            jTextFieldEnd.setText(String.valueOf(conn.rs.getString("endereco")));
            
            conexaoPesquisa.executaSQL("select * from bairro where id_bairro=" +conn.rs.getInt("id_bairro"));          
            conexaoPesquisa.rs.first();
            jComboBoxBairro.setSelectedItem(conexaoPesquisa.rs.getString("nome_bairro"));
            conexaoPesquisa.desconecta();
            conn.desconecta();
            jTextFieldEnd.setEnabled(true);
            jTextFieldNomeForn.setEnabled(true);
            jFormattedTextFieldCNPJ.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);               
        } catch (SQLException s) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ao selecionar os dados! n ERRO:"+s);
            conexaoPesquisa.desconecta();
            conn.desconecta();
        }
        
        
    }//GEN-LAST:event_jTableFornecedorMouseClicked

    private void jButtonPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisar1ActionPerformed
        // TODO add your handling code here:
        FrmBairro  frm = new FrmBairro();
        frm.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisar1ActionPerformed
     
    public void preencherTabela(String SQL){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"ID", "Nome", "Endereco"};
               conn.conexao();
               conn.executaSQL(SQL);
               try{
                  conn.rs.first();
                  do{
                      dados.add(new Object[]{conn.rs.getInt("id_fornecedor"), conn.rs.getString("nome_fornecedor"), conn.rs.getString("endereco")});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTableFornecedor.setModel(modelo);
               jTableFornecedor.getColumnModel ().getColumn(0).setPreferredWidth(60);
               jTableFornecedor.getColumnModel().getColumn(0).setResizable(false);
               jTableFornecedor.getColumnModel ().getColumn(1).setPreferredWidth(240);
               jTableFornecedor.getColumnModel().getColumn(1).setResizable(false);
               jTableFornecedor.getColumnModel ().getColumn(2).setPreferredWidth(255);
               jTableFornecedor.getColumnModel().getColumn(2).setResizable(false);
               jTableFornecedor.getTableHeader().setReorderingAllowed(false);
               jTableFornecedor.setAutoResizeMode(jTableFornecedor.AUTO_RESIZE_OFF);
               jTableFornecedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               conn.desconecta();
               
                
       }
    public void preencherCombobox(){
        conn.conexao();
        conn.executaSQL("select * from bairro order by nome_bairro");
        jComboBoxBairro.removeAllItems();
        try {
            conn.rs.first();
            do{
               jComboBoxBairro.addItem(""+conn.rs.getString("nome_bairro")); 
            }while(conn.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher os bairros!"+ ex);
        }
        conn.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisar1;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JComboBox jComboBoxBairro;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCid;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldEnd;
    private javax.swing.JTextField jTextFieldNomeForn;
    // End of variables declaration//GEN-END:variables
}
