/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloParcelamentoVenda;
import controle.ControleParcelamentoVenda;

/**
 *
 * @author bookafe
 */
public class FrmParcelamentoVenda extends javax.swing.JFrame {
        int qtdParcela,i=1,cont=1;
        float porc, valorVenda, valorParcela;
        ConectaBanco conex = new ConectaBanco();
        ModeloParcelamentoVenda mod = new ModeloParcelamentoVenda();
        ControleParcelamentoVenda control = new ControleParcelamentoVenda();
        
    /**
     * Creates new form FrmParcelamentoVenda
     */
    public FrmParcelamentoVenda(int cod) {
        initComponents();
        
        conex.conexao();
        conex.executaSQL("select * from venda where id_venda ="+cod );
        try {
            conex.rs.first();
            jTextFieldCodVenda.setText(String.valueOf(cod));
            jTextFieldValorVenda.setText(String.valueOf(conex.rs.getFloat("valor_venda")));
            jTextFieldDataVenda.setText(String.valueOf(conex.rs.getString("data_venda")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao buscar a venda"+ex);
        }
        
        
    }

    private FrmParcelamentoVenda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodVenda = new javax.swing.JTextField();
        jTextFieldValorVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldQuantParcelas = new javax.swing.JTextField();
        jTextFieldDataVenda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonParcelar = new javax.swing.JButton();
        jButtonDuplicatas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldJuros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Parcelamento de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Codigo de Venda:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Valor da venda:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Quantidade de parcelas:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Data:");

        jButtonParcelar.setText("Parcelar");
        jButtonParcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcelarActionPerformed(evt);
            }
        });

        jButtonDuplicatas.setText("Gerar duplicatas");
        jButtonDuplicatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDuplicatasActionPerformed(evt);
            }
        });

        tabelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelas);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Valor Total:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Juro das parcelas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldQuantParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jTextFieldJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(96, 96, 96)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jTextFieldCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2))
                            .addGap(108, 108, 108)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(101, 101, 101)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonParcelar)
                            .addGap(36, 36, 36)
                            .addComponent(jButtonDuplicatas))))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuantParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonParcelar)
                    .addComponent(jButtonDuplicatas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(600, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonParcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcelarActionPerformed
        // TODO add your handling code here:
       
        
        qtdParcela = Integer.parseInt(jTextFieldQuantParcelas.getText());
        porc = Float.parseFloat(jTextFieldJuros.getText());
        valorVenda = Float.parseFloat(jTextFieldValorVenda.getText());      
        valorParcela = valorVenda/qtdParcela;
        tabelas.removeAll();
        preencherTabela();
        
    }//GEN-LAST:event_jButtonParcelarActionPerformed

    private void jButtonDuplicatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDuplicatasActionPerformed
        // TODO add your handling code here:
        int j= 1;
        String datavenc= jTextFieldDataVenda.getText();
        String dia,mes,ano;
        dia=""+datavenc.charAt(0)+datavenc.charAt(1)+"/";
       mes=""+datavenc.charAt(3)+datavenc.charAt(4);
       ano="/"+datavenc.charAt(6)+datavenc.charAt(7)+datavenc.charAt(8)+datavenc.charAt(9);             
       int anoInt = Integer.parseInt(""+datavenc.charAt(6)+ datavenc.charAt(7)+datavenc.charAt(8)+datavenc.charAt(9));
       int mesInt = Integer.parseInt(mes);
       
           
                  while(j < cont){
                      
                      
                      if(mesInt<10){
                       mod.setCodVenda(Integer.parseInt(jTextFieldCodVenda.getText()));
                       mod.setValorParcela(valorParcela + (valorParcela*(porc/100)));
                       mod.setValor_total(Float.parseFloat(jTextFieldValorTotal.getText()));
                       mod.setValor_venda(Float.parseFloat(jTextFieldValorVenda.getText()));
                       mod.setNumeroParc(j);
                       mod.setDataVenc(dia + "0"+mesInt + "/" + anoInt);
                      }else{
                       mod.setCodVenda(Integer.parseInt(jTextFieldCodVenda.getText()));
                       mod.setValorParcela(valorParcela + (valorParcela*(porc/100)));
                       mod.setValor_total(Float.parseFloat(jTextFieldValorTotal.getText()));
                       mod.setValor_venda(Float.parseFloat(jTextFieldValorVenda.getText()));
                       mod.setNumeroParc(j);
                       mod.setDataVenc(dia + mesInt + "/" + anoInt);
                       control.SalvaParcela(mod);
                      }
                      mesInt++;
                      if(mesInt >12){
                          anoInt++;
                          mesInt = 1;
                          
                      }
                      j++;
                      
                     
                    
                } 
    }//GEN-LAST:event_jButtonDuplicatasActionPerformed
     
    public void preencherTabela(){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Codigo", "Data", "Valor"};
       float valorAtuParc, valorTotal=0;
       String data=jTextFieldDataVenda.getText();
       String dia,mes,ano;
       dia=""+data.charAt(0)+data.charAt(1)+"/";
       mes=""+data.charAt(3)+data.charAt(4);
       ano="/"+data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9);             
       valorAtuParc = valorParcela+(valorParcela*(porc/100));
       int anoInt = Integer.parseInt(""+data.charAt(6)+ data.charAt(7)+data.charAt(8)+data.charAt(9));
       int mesInt = Integer.parseInt(mes);
       
           
                  while(i <= qtdParcela){
                      
                      valorTotal= valorTotal+valorAtuParc;
                      if(mesInt<10){
                          dados.add(new Object[]{i,dia+ "0" +mesInt+ "/"+anoInt, valorAtuParc});
                      //dados.add(new Object[]{i,dia+(Integer.parseInt(mes)+i)+ano,valorAtuParc});
                      }else{
                          dados.add(new Object[]{i,dia + mesInt + "/"+anoInt, valorAtuParc});
                      }
                      mesInt++;
                      if(mesInt >12){
                          anoInt++;
                          mesInt = 1;
                          
                      }
                      i++;
                      cont++;
                }      
               jTextFieldValorTotal.setText(String.valueOf(valorTotal));
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               tabelas.setModel(modelo);
               tabelas.getColumnModel ().getColumn(0).setPreferredWidth(100);
               tabelas.getColumnModel().getColumn(0).setResizable(false);
               tabelas.getColumnModel ().getColumn(1).setPreferredWidth(230);
               tabelas.getColumnModel().getColumn(1).setResizable(false);
               tabelas.getColumnModel ().getColumn(2).setPreferredWidth(230);
               tabelas.getColumnModel().getColumn(2).setResizable(false);
               tabelas.getTableHeader().setReorderingAllowed(false);
               tabelas.setAutoResizeMode(tabelas.AUTO_RESIZE_OFF);
               tabelas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmParcelamentoVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDuplicatas;
    private javax.swing.JButton jButtonParcelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCodVenda;
    private javax.swing.JTextField jTextFieldDataVenda;
    private javax.swing.JTextField jTextFieldJuros;
    private javax.swing.JTextField jTextFieldQuantParcelas;
    private javax.swing.JTextField jTextFieldValorTotal;
    private javax.swing.JTextField jTextFieldValorVenda;
    private javax.swing.JTable tabelas;
    // End of variables declaration//GEN-END:variables
}
