/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import modelo.ModeloVenda;
import controle.ConectaBanco;
import controle.ControleVendaoriginal;
import controle.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author bookafe
 */
public class FrmVenda extends javax.swing.JFrame {
    ConectaBanco conn = new ConectaBanco();
    ModeloVenda mod = new ModeloVenda();
    controle.ControleVendaoriginal control = new ControleVendaoriginal();
    int flag=1, codVenda;
    float preco_produto,total=0;
    /**
     * Creates new form FrmVenda
     */
    public FrmVenda() {
        initComponents();
        
        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            jFormattedTextFieldData.setFormatterFactory(new DefaultFormatterFactory(form));      
        } catch (ParseException ex) {
             JOptionPane.showMessageDialog(null, "erros ao mostrar dados" + ex);  
            
        }
        // PEGA DATA DO SISTEMA
        jTextFieldProduto.setDocument(new teclasPermitidas.TeclasPermitidasMaiusculas());
        
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(df.format(hoje));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jButtonBuscaCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jButtonBuscaProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldValorItem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItensVendas = new javax.swing.JTable();
        jButtonFinVenda = new javax.swing.JButton();
        jButtonCancVenda = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxPagamento = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de vendas");
        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Formulário de vendas");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Nome do cliente ou numero da mesa:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Data:");

        jFormattedTextFieldData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldData.setEnabled(false);
        jFormattedTextFieldData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataFocusGained(evt);
            }
        });

        jButtonBuscaCliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonBuscaCliente.setText("Busca");
        jButtonBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaClienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Produto:");

        jButtonBuscaProduto.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonBuscaProduto.setText("Busca");
        jButtonBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Quantidade:");

        jTextFieldQuantidade.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextFieldQuantidade.setForeground(new java.awt.Color(51, 0, 255));
        jTextFieldQuantidade.setCaretColor(new java.awt.Color(0, 0, 204));
        jTextFieldQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQuantidadeFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Valor item:");

        jLabel7.setText("Valor Total:");

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisa);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Tabela de Pesquisa");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Itens da venda:");

        jTableItensVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableItensVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensVendasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableItensVendas);

        jButtonFinVenda.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonFinVenda.setText("FinalizarVenda");
        jButtonFinVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinVendaActionPerformed(evt);
            }
        });

        jButtonCancVenda.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonCancVenda.setText("Cancelar Venda");
        jButtonCancVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancVendaActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Tipo de pagamento:");

        jComboBoxPagamento.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jComboBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A vista", "Parcelado" }));
        jComboBoxPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxPagamentoMouseClicked(evt);
            }
        });
        jComboBoxPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFinVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancVenda)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBuscaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBuscaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldProduto)))
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaProduto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFinVenda)
                    .addComponent(jButtonCancVenda)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutoActionPerformed
        // TODO add your handling code here:
        conn.conexao();
        try {
            PreparedStatement pst = conn.conn.prepareStatement("insert into venda (valor_venda) values(?)");
            pst.setFloat(1, 0);
            pst.execute();
            conn.executaSQL("select * from venda");
            conn.rs.last();
            codVenda=conn.rs.getInt("id_venda");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro" + ex);  
        }
        flag=2;
        preencherTabelaProduto("select * from produto where nome_produto like '%" +jTextFieldProduto.getText()+ "%'");
    }//GEN-LAST:event_jButtonBuscaProdutoActionPerformed

    private void jButtonBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaClienteActionPerformed
        // TODO add your handling code here:
        flag=1;
        preencherTabelaCliente("select * from clientes where nome_cliente like '%" +jTextFieldCliente.getText()+ "%'");
    }//GEN-LAST:event_jButtonBuscaClienteActionPerformed

    private void jTablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseClicked
        // TODO add your handling code here:
        if (flag==1){
            String nome_cliente = "" +jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(),1);
            jTextFieldCliente.setText(nome_cliente);
        }
        else{
            try {
                String nome_produto = "" +jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(),1);
                conn.executaSQL("select * from produto where nome_produto='"+nome_produto+"'");
                conn.rs.first(); 
                preco_produto = conn.rs.getFloat("preco_venda");
                jTextFieldProduto.setText(nome_produto);
                jTextFieldValorItem.setText(String.valueOf(preco_produto));
                jTextFieldQuantidade.setText("1");
                conn.desconecta();
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar o preço:"+ex);
            }
        }
    }//GEN-LAST:event_jTablePesquisaMouseClicked

    private void jTextFieldQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeFocusGained
        // TODO add your handling code here:
        float valorTotal;
        valorTotal= Float.parseFloat(jTextFieldValorItem.getText())*Integer.parseInt(jTextFieldQuantidade.getText());
        jTextFieldValorTotal.setText(String.valueOf(valorTotal));
    }//GEN-LAST:event_jTextFieldQuantidadeFocusGained

    private void jFormattedTextFieldDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataFocusGained
        // TODO add your handling code here:
        float valorTotal;
        valorTotal= Float.parseFloat(jTextFieldValorItem.getText())*Integer.parseInt(jTextFieldQuantidade.getText());
        jTextFieldValorTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jFormattedTextFieldDataFocusGained

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        try {
            // TODO add your handling code here:
            int Venda,quantidadeBanco=0;
            int idVenda;
            int resul;
            int quantidadeForm;
            
            conn.conexao();
            conn.executaSQL("select * from produto where nome_produto='"+jTextFieldProduto.getText()+"'");
            conn.rs.first();
            
            quantidadeBanco = conn.rs.getInt("quantidade");// pegar valor numerico do banco de dados
            quantidadeForm = Integer.parseInt(jTextFieldQuantidade.getText()); // Pegar valor numerico do formulário através de um TextField
            
            if(quantidadeBanco >= quantidadeForm){
            //if(quantidade>=Integer.parseInt(jTextFieldQuantidade.getText())){
            resul = quantidadeBanco - quantidadeForm;
            mod.setNomeProduto(jTextFieldProduto.getText());
            mod.setQtdItem(Integer.parseInt(jTextFieldQuantidade.getText()));
            mod.setIdVenda(codVenda);
            control.adicionaItem(mod);
            
            
            preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda="+ codVenda);
            } else{
                 JOptionPane.showMessageDialog(rootPane,"A quantidade desejada nao estar disponivel no estoque");
            }
            //total=total+Float.parseFloat(jTextFieldValorItem.getText())*Integer.parseInt(jTextFieldQuantidade.getText());
            //jTextFieldValorTotal.setText(String.valueOf(total));
            //preencherItensVenda("select * from produto inner join itens_venda_produto on produto.id_produto= itens_venda_produto.id_produto inner join venda on venda.id_venda=itens_venda_produto.id_venda where venda.id_venda="+ codVenda);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonFinVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinVendaActionPerformed
        // TODO add your handling code here:
        if(jComboBoxPagamento.getSelectedItem().equals("A vista")){
        mod.setIdVenda(codVenda);
        mod.setMesaCliente(jTextFieldCliente.getText());
        mod.setData(jFormattedTextFieldData.getText());
        mod.setValorVenda(Float.parseFloat(jTextFieldValorTotal.getText()));
        mod.setPagamento((String)jComboBoxPagamento.getSelectedItem());
        control.FechaVenda(mod);
        dispose();
        }else{
           
        mod.setIdVenda(codVenda);
        mod.setMesaCliente(jTextFieldCliente.getText());
        mod.setData(jFormattedTextFieldData.getText());
        mod.setValorVenda(Float.parseFloat(jTextFieldValorTotal.getText()));
        mod.setPagamento((String)jComboBoxPagamento.getSelectedItem());
        control.FechaVenda(mod);
        FrmParcelamentoVenda frm = new FrmParcelamentoVenda(codVenda);
        frm.setVisible(true);
        dispose();  
        }
    }//GEN-LAST:event_jButtonFinVendaActionPerformed

    private void jButtonCancVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancVendaActionPerformed
        // TODO add your handling code here:
        control.CancelaVenda();
        dispose();
    }//GEN-LAST:event_jButtonCancVendaActionPerformed

    private void jTablePesquisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePesquisaMouseEntered

    private void jComboBoxPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxPagamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagamentoMouseClicked

    private void jComboBoxPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagamentoActionPerformed

    private void jTableItensVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensVendasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableItensVendasMouseClicked

    public void preencherTabelaCliente(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Codigo", "Nome"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      
                      dados.add(new Object[]{conn.rs.getString("id_cliente"), conn.rs.getString("nome_cliente")});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTablePesquisa.setModel(modelo);
               jTablePesquisa.getColumnModel ().getColumn(0).setPreferredWidth(100);
               jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
               jTablePesquisa.getColumnModel ().getColumn(1).setPreferredWidth(330);
               jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
               jTablePesquisa.getTableHeader().setReorderingAllowed(false);
               jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
               jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
       }
    public void preencherTabelaProduto(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Codigo", "Nome","Qtd"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      dados.add(new Object[]{conn.rs.getString("id_produto"), conn.rs.getString("nome_produto"),conn.rs.getString("quantidade")});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTablePesquisa.setModel(modelo);
               jTablePesquisa.getColumnModel ().getColumn(0).setPreferredWidth(100);
               jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
               jTablePesquisa.getColumnModel ().getColumn(1).setPreferredWidth(430);
               jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
               jTablePesquisa.getColumnModel ().getColumn(2).setPreferredWidth(100);
               jTablePesquisa.getColumnModel().getColumn(2).setResizable(false);
               jTablePesquisa.getTableHeader().setReorderingAllowed(false);
               jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
               jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
       }
    
    public void preencherItensVenda(String sql){
       ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[] {"Descricao", "Quantidade","Valor total"};
               conn.conexao();
               conn.executaSQL(sql);
               //conn.executaSQL("select * from clientes where nome_cliente =%'"+jTextFieldCliente.getText()+"'%");
               try{
                  conn.rs.first();
                  do{
                      float valorProduto = conn.rs.getFloat("preco_venda");
                      int qtdVendida = conn.rs.getInt("quantidade_produto");
                      dados.add(new Object[]{conn.rs.getString("nome_produto"), conn.rs.getString("quantidade_produto"),valorProduto * qtdVendida});
              }while(conn.rs.next());       
                 }catch (SQLException ex){
                     JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
                   }  
               ModeloTabela modelo = new ModeloTabela(dados, Colunas);
               jTableItensVendas.setModel(modelo);
               jTableItensVendas.getColumnModel ().getColumn(0).setPreferredWidth(100);
               jTableItensVendas.getColumnModel().getColumn(0).setResizable(false);
               jTableItensVendas.getColumnModel ().getColumn(1).setPreferredWidth(330);
               jTableItensVendas.getColumnModel().getColumn(1).setResizable(false);
               jTableItensVendas.getColumnModel ().getColumn(1).setPreferredWidth(100);
               jTableItensVendas.getColumnModel().getColumn(1).setResizable(false);
               jTableItensVendas.getTableHeader().setReorderingAllowed(false);
               jTableItensVendas.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
               jTableItensVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               SomaProduto();
                
       }
    
    public void SomaProduto(){
        float total= 0;
        int qtd=0;
        float valor=0;
     
        conn.executaSQL("select * from itens_venda_produto inner join produto on itens_venda_produto.id_produto=produto.id_produto where id_venda="+codVenda);
        try {
            //conn.rs.first();
            while(conn.rs.next()){
                qtd = conn.rs.getInt("quantidade");
                valor = conn.rs.getFloat("preco_venda");
                total = total+ conn.rs.getFloat("preco_venda")* conn.rs.getInt("quantidade_produto");
                
            }
            jTextFieldValorTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array list! n ERRO:"+ex);
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBuscaCliente;
    private javax.swing.JButton jButtonBuscaProduto;
    private javax.swing.JButton jButtonCancVenda;
    private javax.swing.JButton jButtonFinVenda;
    private javax.swing.JComboBox jComboBoxPagamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableItensVendas;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldValorItem;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
