/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.AtualizadorHora;
import controle.ConectaBanco;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import visao.FormLogin2;
/**
 *
 * @author bookafe
 */
public class PrincipalMain extends javax.swing.JFrame {
    DecimalFormat formato;
   ConectaBanco conecta = new ConectaBanco();
    private Object jaspeFillManager;
    private Object JaspeFillManager;
  
    public PrincipalMain(String users) {
        initComponents();
        formato = new DecimalFormat("#0.00");
        //comando para maximizar a tela
        
        //this.setExtendedState(this.getExtendedState()|PrincipalMain.MAXIMIZED_BOTH);
        conecta.conexao();
        jLabelUser.setText(users);
        AtualizadorHora.start(jLabelHorario);
        
        conecta.executaSQL("select * from vencimento");
       try {
           conecta.rs.last();
           
           char[] data = conecta.rs.getString("datavencimento").toCharArray();
           
           jLabelLicenca.setText("O Sistema expira dia:"+data[0]+""+data[1]+"/"+data[2]+""+data[3]+"/"+data[4]+data[5]+data[6]+data[7]);
           jLabelLicenca.setText("");
       } catch (SQLException ex) {
          
       }
    }

    private PrincipalMain() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

//    public PrincipalMain() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLicenca = new javax.swing.JLabel();
        jLabelteste = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabelHorario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemCidade = new javax.swing.JMenuItem();
        jMenuItemBairro = new javax.swing.JMenuItem();
        jMenuItemTelefone = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemValidSist = new javax.swing.JMenuItem();
        jMenuItemLiberaSist = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItemPagarParcela = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/bookafe/Desktop/CAFE.jpeg")); // NOI18N
        jLabel1.setText("                                      Bookafe Genève");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jButton1.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jButton1.setText("Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1017, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        jLabelUser.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(204, 0, 0));
        jLabelUser.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabelLicenca.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelLicenca.setText("Licença:");

        jLabelteste.setText("TESTE");

        jButton2.setText("ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        label.setForeground(new java.awt.Color(204, 0, 51));
        label.setText("Hora:");

        jLabelHorario.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabelHorario.setForeground(new java.awt.Color(0, 0, 153));
        jLabelHorario.setText("jLabel4");

        jMenu1.setText("Cadastros");

        jMenuItem1.setText("Estados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItemCidade.setText("Cidades");
        jMenuItemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCidade);

        jMenuItemBairro.setText("Bairro");
        jMenuItemBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBairroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemBairro);

        jMenuItemTelefone.setText("Telefones");
        jMenuItemTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelefoneActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTelefone);

        jMenuItemCliente.setText("Clientes");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCliente);

        jMenuItemFornecedor.setText("Fornecedores");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFornecedor);

        jMenuItemProdutos.setText("Produtos");
        jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProdutos);

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemClientes);

        jMenuItemUsuario.setText("Usuario");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuario);

        jMenuItemValidSist.setText("Validação do sistema");
        jMenuItemValidSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidSistActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemValidSist);

        jMenuItemLiberaSist.setText("Liberação do Sistema");
        jMenuItemLiberaSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLiberaSistActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLiberaSist);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Venda");

        jMenuItem11.setText("Formulario de Venda");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItemPagarParcela.setText("PagarParcela");
        jMenuItemPagarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagarParcelaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPagarParcela);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        jMenuItem8.setText("Cliente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem2.setText("Cidade");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sair");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2397, 2397, 2397)
                        .addComponent(jLabelLicenca)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(67, 67, 67)
                        .addComponent(jLabelteste)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label)
                .addGap(52, 52, 52)
                .addComponent(jLabelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelHorario)))
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jLabelLicenca)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabelteste))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser)
                            .addComponent(jLabel2))
                        .addContainerGap())))
        );

        setSize(new java.awt.Dimension(1577, 904));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
      
        try {
           // TODO add your handling code here:
           conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Administrador")){
                 FrmEstado frm = new FrmEstado();
                 frm.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
               
           }
       } catch (SQLException ex) {
           
       }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCidadeActionPerformed
        
        try {
           // TODO add your handling code here:
           conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Administrador")){
               FrmCidade frm = new FrmCidade();
               frm.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
               
           }
       } catch (SQLException ex) {
          
       }

    }//GEN-LAST:event_jMenuItemCidadeActionPerformed

    private void jMenuItemBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBairroActionPerformed
        
        try {
           // TODO add your handling code here:
           conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Administrador")){
               FrmBairro frm = new FrmBairro();
                frm.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
               
           }
       } catch (SQLException ex) {
           
       }
    }//GEN-LAST:event_jMenuItemBairroActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        // TODO add your handling code here:
        
        try {
           // TODO add your handling code here:
           conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Administrador")){
               FrmFornecedor frm = new FrmFornecedor();
               frm.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
               
           }
       } catch (SQLException ex) {
           
       }
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        conecta.desconecta();
        System.exit(0);

    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItemTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelefoneActionPerformed
        // TODO add your handling code here:
        FrmTelefone frm = new FrmTelefone();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelefoneActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        try {
           // TODO add your handling code here:
           conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Administrador")){
                FrmClientes frm = new FrmClientes();
                 frm.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
               
           }
       } catch (SQLException ex) {
           
       }
       
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
       try {
           // TODO add your handling code here:
           conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Administrador")){
               FrmProduto frm = new FrmProduto();
               frm.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
               
           }
       } catch (SQLException ex) {
           
       }
    }//GEN-LAST:event_jMenuItemProdutosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmCardapio frm = new FrmCardapio();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        try {
         conecta.executaSQL("select * from clientes");
        JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/relatorioBrancoCliente.jasper",new HashMap(), relatResul);
        JasperViewer jv = new JasperViewer(jpPrint,false);      
        jv.setVisible(true);
        jv.toFront();
        
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao achar cliente n ERRO:" + ex);
        }
       
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        // TODO add your handling code here:
         FrmClientes frm = new FrmClientes();
         frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        // TODO add your handling code here:
       
       try {
            conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Administrador")){
          FormLogin2 frm = new FormLogin2();
           frm.setVisible(true);
          }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
            
        }
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
       }
        
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        FrmVenda frm = new FrmVenda();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItemLiberaSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLiberaSistActionPerformed
        // TODO add your handling code here:
        try {
            conecta.executaSQL("select * from login where login ='"+jLabelUser.getText()+"'");
           conecta.rs.first();
           if(conecta.rs.getString("permissao").equals("Desenvolvedor")){
        FrmCadDataVenciSistema frm = new FrmCadDataVenciSistema();
        frm.setVisible(true);
        }else{
               JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
            
        }
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane," voce nao possui permissao");
       }
    }//GEN-LAST:event_jMenuItemLiberaSistActionPerformed

    private void jMenuItemValidSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidSistActionPerformed
        // TODO add your handling code here:
        FrmValidaSist frm = new FrmValidaSist();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemValidSistActionPerformed

    private void jMenuItemPagarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagarParcelaActionPerformed
        // TODO add your handling code here:
        FrmBaixaParcela frm = new FrmBaixaParcela();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemPagarParcelaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //formato = new DecimalFormat("#0.00");
        Double num = 12.977777;
        jLabelteste.setText(formato.format(num));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
          try {
         conecta.executaSQL("select * from cidade");
        JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/relatorioBrancoCliente.jrxml",new HashMap(), relatResul);
        JasperViewer jv = new JasperViewer(jpPrint,false);      
        jv.setVisible(true);
        jv.toFront();
        
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao achar cliente n ERRO:" + ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
          FrmCardapio frm = new FrmCardapio();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 PrincipalMain frm = new PrincipalMain();
                 frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelLicenca;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelteste;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemBairro;
    private javax.swing.JMenuItem jMenuItemCidade;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemLiberaSist;
    private javax.swing.JMenuItem jMenuItemPagarParcela;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemTelefone;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenuItem jMenuItemValidSist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
